# Generated by Django 5.2.6 on 2025-09-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_create_asset_logs_unified_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetlogunified',
            options={'managed': False, 'ordering': ['-trade_date']},
        ),
    ]
