# Generated by Django 5.2.6 on 2025-09-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_assetlogunified_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portfoliosnapshot',
            name='pk_snapshot_poly',
        ),
        migrations.RemoveConstraint(
            model_name='portfoliosnapshot',
            name='chk_snap_polykey',
        ),
        migrations.AddField(
            model_name='portfolioholding',
            name='asset_key',
            field=models.TextField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='asset_key',
            field=models.TextField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliosnapshot',
            unique_together={('user_id', 'snapshot_date', 'asset_key')},
        ),
    ]
