# Generated by Django 5.2.6 on 2025-09-09 01:42

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_portfoliosnapshot_pk_snapshot_poly_and_more'),
    ]

    operations = [
        # 1) 백필 (SQLite 테이블명 기준)
        migrations.RunSQL(
            "UPDATE dashboard_portfolioholding "
            "SET asset_key = CASE "
            "  WHEN stock_ticker_symbol IS NOT NULL AND property_info_id IS NULL THEN 'stock:' || stock_ticker_symbol "
            "  WHEN property_info_id IS NOT NULL AND stock_ticker_symbol IS NULL THEN 're:' || CAST(property_info_id AS TEXT) "
            "  ELSE asset_key END "
            "WHERE asset_key IS NULL;"
        ),
        migrations.RunSQL(
            "UPDATE dashboard_portfoliosnapshot "
            "SET asset_key = CASE "
            "  WHEN stock_ticker_symbol IS NOT NULL AND property_info_id IS NULL THEN 'stock:' || stock_ticker_symbol "
            "  WHEN property_info_id IS NOT NULL AND stock_ticker_symbol IS NULL THEN 're:' || CAST(property_info_id AS TEXT) "
            "  ELSE asset_key END "
            "WHERE asset_key IS NULL;"
        ),

        # 2) NOT NULL 전환
        migrations.AlterField(
            model_name='portfolioholding',
            name='asset_key',
            field=models.TextField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='asset_key',
            field=models.TextField(db_index=True, editable=False),
        ),

        # 3) (이미 들어간) 스냅샷 체크 제약 유지
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.CheckConstraint(
                name='chk_snap_poly_exactly_one_key',
                condition=models.Q(
                    models.Q(('property_info_id__isnull', True), ('stock_ticker_symbol__isnull', False)) |
                    models.Q(('property_info_id__isnull', False), ('stock_ticker_symbol__isnull', True))
                ),
            ),
        ),
    ]

