# Generated by Django 5.2.6 on 2025-09-09 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_portfolioholding_asset_key_and_more'),
    ]

    operations = [
    ]
