# Generated by Django 5.2.6 on 2025-09-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_recreate_asset_logs_unified_view_sqlite'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portfoliosnapshot',
            name='chk_snap_poly_exactly_one_key',
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('property_info_id__isnull', True), ('stock_ticker_symbol__isnull', False)), models.Q(('property_info_id__isnull', False), ('stock_ticker_symbol__isnull', True)), _connector='OR'), name='chk_snap_poly_exactly_one_key'),
        ),
    ]
