# Generated by Django 5.2.6 on 2025-09-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_portfoliosnapshot_chk_snap_poly_exactly_one_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioholding',
            unique_together={('user_id', 'asset_key')},
        ),
        migrations.AddIndex(
            model_name='portfolioholding',
            index=models.Index(fields=['user_id'], name='dashboard_p_user_id_470b05_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioholding',
            index=models.Index(fields=['user_id', 'sector_or_region'], name='dashboard_p_user_id_c8cbfb_idx'),
        ),
    ]
