# Generated by Django 5.2.6 on 2025-09-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('my_ID', models.CharField(max_length=50, unique=True, verbose_name='사용자 아이디')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일 주소')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/', verbose_name='프로필 사진')),
                ('background_picture', models.ImageField(blank=True, upload_to='background_pictures/', verbose_name='배경 사진')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
