# Generated by Django 5.2.6 on 2025-09-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalpost',
            name='visibility',
        ),
        migrations.AddField(
            model_name='journalpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/'),
        ),
    ]
