# Generated by Django 5.2.6 on 2025-09-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['-is_default', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='journalpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='home.tag'),
        ),
    ]
