# Generated by Django 5.2.6 on 2025-09-11 02:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='REPropertyInfo',
            fields=[
                ('property_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_type', models.CharField(max_length=50)),
                ('building_name', models.CharField(max_length=255)),
                ('address_base', models.CharField(max_length=255)),
                ('lawd_cd', models.CharField(max_length=5)),
                ('dong', models.CharField(max_length=50)),
                ('build_year', models.IntegerField(blank=True, null=True)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('total_floor', models.IntegerField(blank=True, null=True)),
                ('total_units', models.IntegerField(blank=True, null=True)),
                ('exclusive_types', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('ticker_symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('last_close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='REDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('매매', '매매'), ('전세', '전세'), ('월세', '월세')], max_length=10)),
                ('contract_date', models.DateField()),
                ('amount_main', models.DecimalField(decimal_places=0, max_digits=18)),
                ('amount_deposit', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('amount_monthly', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('floor', models.IntegerField()),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('loan_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fees_broker', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('tax_acq', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('reg_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('misc_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('raw_snapshot_json', models.JSONField(default=dict)),
                ('snapshot_source', models.CharField(blank=True, max_length=20)),
                ('snapshot_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_deals', to=settings.AUTH_USER_MODEL)),
                ('property_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='journals.repropertyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StockJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('stop_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total_buy_qty', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=18)),
                ('total_sell_qty', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=18)),
                ('avg_buy_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('avg_sell_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('net_qty', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=18)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('return_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker_symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='journals.stockinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_journals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('asset_class', models.CharField(choices=[('stock', 'Stock'), ('realestate', 'Real Estate')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('screenshot_url', models.URLField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_posts', to=settings.AUTH_USER_MODEL)),
                ('re_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='journals.redeal')),
                ('stock_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='journals.stockjournal')),
            ],
        ),
        migrations.CreateModel(
            name='StockTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('trade_date', models.DateField()),
                ('price_per_share', models.DecimalField(decimal_places=4, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fee_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='journals.stockjournal')),
                ('ticker_symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='journals.stockinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='redeal',
            index=models.Index(fields=['user', 'property_info'], name='journals_re_user_id_1a78b4_idx'),
        ),
        migrations.AddIndex(
            model_name='redeal',
            index=models.Index(fields=['contract_date'], name='journals_re_contrac_2faf68_idx'),
        ),
        migrations.AddIndex(
            model_name='stockjournal',
            index=models.Index(fields=['user', 'ticker_symbol'], name='journals_st_user_id_658d24_idx'),
        ),
        migrations.AddIndex(
            model_name='journalpost',
            index=models.Index(fields=['user', 'visibility', 'created_at'], name='journals_jo_user_id_2087a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalpost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset_class', 'stock'), ('re_deal__isnull', True), ('stock_journal__isnull', False)), models.Q(('asset_class', 'realestate'), ('re_deal__isnull', False), ('stock_journal__isnull', True)), _connector='OR'), name='stock_journal_or_re_deal_is_set'),
        ),
        migrations.AddIndex(
            model_name='stocktrade',
            index=models.Index(fields=['journal', 'trade_date'], name='journals_st_journal_93e7b9_idx'),
        ),
    ]
