# Generated by Django 5.2.6 on 2025-09-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repropertyinfo',
            name='lawd_cd',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
